### ISSUE TITLE
Great job!

### ISSUE THREAD

**Issue by ConsoleTVs** [w00p/startup#19]
Hello! I'm also the developer of Laralum (https://github.com/ConsoleTVs/Laralum) Something similar to that! I was wondering how did you manage the "online" feature!? 💃

**Comment by w00p** [comment]
Make a middleware: https://github.com/w00p/startup/blob/master/app/Http/Middleware/LogLastUserActivity.php

Then add it to the kernel.php: 
`\App\Http\Middleware\LogLastUserActivity::class,`.
(It is important that it’s added after the StartSession middleware)

Add this to the user object in App\User; 

```
public function isOnline()
{
    return Cache::has('user-is-online-' . $this->id);
}
```

Now in your views you can do something like this.

```
@if($user->isOnline())
    user is online!!
@endif
```

**Comment by ConsoleTVs** [comment]
Damn! Thanks a lot! I'll try to get your example, but I'm making sure it works!

**Comment by w00p** [comment]
No problem :)

**Comment by ConsoleTVs** [comment]
Did you find urself a solution or I may continue developing the example?

```
Charts::new('line', 'highcharts')
            ->setTitle("My website users")
            ->setLabels(['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'])
            ->setValues([100, 50, 100, 50, 100, 50, 100, 50, 100, 50, 100, 50])
            ->setElementLabel("Total users");
```

You just need to change the values to the corresponding ones!
