### ISSUE TITLE
Merging projects!

### ISSUE THREAD

**Issue by ConsoleTVs** [w00p/startup#20]
Hey w00p, you already know me, today I was looking at your project once again and I finally came to ask you if you would like to merge our projects.

Listen up!

You created a startup project pretty neat and simple, while I did the same with the current Laralum version.

I'm currently trying to create laralum as a modular project. People will install it as a regular package and then they will be able to add modules that are created separated.

Since the base idea is found in your project, I'm asking if you would be interested in create something like this with me.

**Comment by w00p** [comment]
Hi, as for now i think i will keep my own little prosject. 
I dont have that much time right now. 

Sorry. But i will keep you updated if i change my mind :)

**Comment by ConsoleTVs** [comment]
Sure okay!
