### ISSUE TITLE
spatie/activitylog instead of spatie/laravel-activitylog

### ISSUE THREAD

**Issue by godxavia** [w00p/startup#23]
I have a problem with spatie/laravel-activitylog, it needs ^PHP7
so i use spatie/activitylog instead 

then when I try to log in the error said 
"Call to undefined function App\Http\Controllers\Auth\activity()"

I'm so noob and need help,
Thanks

**Comment by w00p** [comment]
You have to use php 7.0 to get this to work. All packages from spatie use php 7.0. I have updated readme with correct php version.

**Comment by godxavia** [comment]
Then you should change your requirement to >= PHP 7.0 ;)

**Comment by w00p** [comment]
Yes, sorry about that, its done now ;)
